- .github/workflows/test-py39-functional.yaml
- ci/mapping.json
- ci/run_functional_tests.sh
- ci/setup.sh
- setup.cfg
- setup.py
- src/coldfront_plugin_openstack/attributes.py
- src/coldfront_plugin_openstack/management/commands/add_openstack_resource.py
- src/coldfront_plugin_openstack/management/commands/register_openstack_attributes.py
- src/coldfront_plugin_openstack/tasks.py
- src/coldfront_plugin_openstack/tests/base.py
- src/coldfront_plugin_openstack/tests/functional/test_allocation.py
- src/coldfront_plugin_openstack/tests/test_resource_allocation.py
- src/local_settings.py
Reviewing is easier when going commit by commit, as most of them are pretty self-contained. When going down like that, there are some bugs however, which were introduced during refactoring and only caught by the [commit that introduces  testing](https://github.com/nerc-project/coldfront-plugin-openstack/commit/72516cd8e27dbc8e9a93c4b496819404398a404f).
Closes #2
Partial #1
> Implement structure for quotas and functional testing

- ci/setup.sh
- src/coldfront_plugin_openstack/tasks.py
- src/coldfront_plugin_openstack/tests/functional/test_allocation.py
- PI was not being added on activation allocation. This change
fixes that with some small refactoring of the create user and
role assignment methods. Augmented tests for this case.
- CI was broken since Microstack moved to requiring self-signed
HTTPS. This fixes that by adding a check to the
FUNCTIONAL_TESTS='True' environment variable.
Closes #6 
Closes #10
> Add PI on allocation activation and fix CI

- src/coldfront_plugin_openstack/tasks.py
- src/coldfront_plugin_openstack/tests/functional/test_allocation.py
- When failing the query by unique_id, query for the username and
add that user to the project. The user may be a not federated user.
Closes #9
> Fix conflict when user already exists

- src/coldfront_plugin_openstack/tasks.py
user should have been assigned to the return value of
get_federated_user, not to the result of the comparison.
> Fix incorrect use of assignment expression

- .github/workflows/test-py39-functional.yaml
- src/coldfront_plugin_openstack/signals.py
- src/coldfront_plugin_openstack/tasks.py
- test-requirements.txt
- The unique_id parsed by keystone for federated users logging in
to the NERC is url encoded (based on what I observed testing).
Therefore the create users call should url encode the unique
id as well.
- Updated the coldfront has in test-requirements to match latest
Coldfront master.
- Added a conditional to async_task so that the task isn't attempting
to run asynchronously unless Django-Q is configured.
> Url encode unique_id in create_user call

- .github/workflows/test-py38-functional-devstack.yaml
- .github/workflows/test-py39-functional.yaml
- Vagrantfile
- ci/devstack.sh
- ci/run_functional_tests.sh
- ci/setup.sh
- setup.cfg
- src/coldfront_plugin_openstack/tests/functional/test_allocation.py
- Install Devstack with the OpenID Connect plugin from
https://github.com/knikolla/devstack-plugin-oidc
- Lower python requirement to 3.8
> Add Devstack job to CI with OIDC

- .github/workflows/test-py39-functional.yaml
- ci/run_functional_tests.sh
- src/coldfront_plugin_openstack/attributes.py
- src/coldfront_plugin_openstack/management/commands/add_openstack_resource.py
- src/coldfront_plugin_openstack/tasks.py
- src/coldfront_plugin_openstack/tests/base.py
- src/coldfront_plugin_openstack/tests/functional/test_allocation.py
- Added attribute 'OpenStack Public Network ID'
- Added attribute 'OpenStack Default Network CIDR'
- Default network DNS set to Google DNS
- Added simple test case of network created
Closes #21
> Create default network when provisioning project

- src/coldfront_plugin_openstack/tests/base.py
Rather than directly creating the Resource from the model,
use the command line interface. This should prevent breakages
in the command that happened previously by the lack of testing
for that part of the codebase.
Closes #25
> Use call_method on add_openstack_resource in tests

- ci/devstack.sh
- ci/run_functional_tests.sh
- src/coldfront_plugin_openstack/attributes.py
- src/coldfront_plugin_openstack/management/commands/register_openstack_attributes.py
- src/coldfront_plugin_openstack/signals.py
- src/coldfront_plugin_openstack/tasks.py
- src/coldfront_plugin_openstack/tests/functional/test_allocation.py
- src/coldfront_plugin_openstack/utils.py
- test-requirements.txt
Closes #1 
- Persist current quota as allocation attribute on activation
- Also adds exit on error for run_functional_tests.sh
- Also adds a conditional to installing docker-compose for when
running on vagrant.
- Added support for floating ips
- Refactored some of the common code for setting quotas
- Refactored the testing code for quotas to be more easy to read
- Renamed and updated utils.add_allocation_attribute to
utils.get_allocation_attribute and now it supports updating
existing allocation attributes
- Added a receiver for allocation_change_approval to
activate_allocation.
> Support allocation changes and networking quota

- src/coldfront_plugin_openstack/attributes.py
- src/coldfront_plugin_openstack/tasks.py
Adds an attribute to track GPU quota. Does not apply the quota to any service, just tracks it.
> Add attribute to track GPU quota

- .github/workflows/test-py39-unit.yaml
- ci/run_unit_tests.sh
- src/coldfront_plugin_openstack/management/commands/register_cloud_attributes.py
- src/coldfront_plugin_openstack/tests/unit/test_attribute_migration.py
It is now possible to define a list of attributes that will be
automatically renamed when running the above management command.
Additionally, this creates a new github action to run the
newly necessary unit tests.
Closes #42
> Rename attributes in register_cloud_attributes command

- src/coldfront_plugin_openstack/openshift.py
Add pi information as annotation metadata for openshift resources. This will be useful for later metric data consumption in xdmod.
> Annotations

- src/coldfront_plugin_openstack/base.py
- src/coldfront_plugin_openstack/management/commands/validate_allocations.py
- src/coldfront_plugin_openstack/openshift.py
- src/coldfront_plugin_openstack/openstack.py
- src/coldfront_plugin_openstack/tests/base.py
- src/coldfront_plugin_openstack/tests/functional/openshift/test_allocation.py
- src/coldfront_plugin_openstack/tests/functional/openstack/test_allocation.py
- The ResourceAllocator base class now defines get_quota and the OpenStack
resource allocator implements the method.
- Currently limited to OpenStack resources, the `validate_allocations` command
checks that the output of get_quota on an allocation, matches the value of the quota
attributes.
> Implement get_quota and initial implementation of validate_allocations

- src/coldfront_plugin_cloud/openstack.py
- Rework how we "switch projects" to avoid templating issues between various endpoint URL implementations (e.g. devstack using `$` vs RHOSP using `%` for template variables). This issue has resulted in 403 forbidden errors connecting to swift on RHOSP.
- Handle case where swift `head_account` is missing the quota key
> fix swift quotas

- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/management/commands/register_cloud_attributes.py
- src/coldfront_plugin_cloud/tests/unit/test_attribute_migration.py
The following Resource attributes are migrated
- OpenStack Auth URL -> Identity Endpoint URL
- OpenStack Role for User in Project -> Role for User in Project
The following Allocation attributes are migrated
- OpenStack Project Name -> Allocated Project Name
- OpenStack Project ID -> Allocated Project ID
The choice of allocated is to signal that the allocation has
been completed on the service.
Additionaly, a test has been added to verify that the migration
of resource attributes preserves the value of the attribute.
Closes #59
> Rename attributes to remove OpenStack prefix

- ci/setup.sh
An update to `setuptools` broke `pip`. This updates `pip` to pick up the fix, and in turn fix our CI.
> Update pip package in CI setup

- src/coldfront_plugin_cloud/openstack.py
When a user is created in between of get and create, the create command is going to fail with 409 Conflict.
In case that happens, just query again the user and return it.
Closes #82
> Handle possible race conditions on user create

- src/coldfront_plugin_cloud/base.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/openstack.py
- src/coldfront_plugin_cloud/tasks.py
- src/coldfront_plugin_cloud/tests/unit/test_utils.py
- src/coldfront_plugin_cloud/utils.py
This commit moves `get_unique_project_name` to `utils.py` and then use that when generating the name. It also adds a check to the method to validate the project name.
> Include Coldfront project name when generating project display name

- .github/workflows/test-py39-functional-microshift.yaml
- ci/microshift.sh
- ci/setup-oc-client.sh
- ci/setup-ubuntu.sh
This is a series of changes to make it easier to run the CI tests in a local Linux environment. In particular:
- We move more configuration into environment variables
- We move distribution-specific package installs to a separate script
- We avoid conflicts with host services running on the same ports used by Microshift and the image registry
- We make it possible to run the tests without clobbering a local `~/.kube/config` file
> Make it easier to run CI locally

- README.md
- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/tasks.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
Adds support for
- limits
- persistentvolumeclaims
Sets the defaults to 10Gi storage and 2 volumes.
Closes #78
> Add support for setting storage and pvc quotas

- src/coldfront_plugin_cloud/tests/unit/test_utils.py
- src/coldfront_plugin_cloud/utils.py
There was an extraneous `f` symbol which added 1 to the length.
Added tests to verify the fix.
Closes #96
> Fix issue with length of names generated

- ci/devstack.sh
Instead of master, this may be more stable going forward.
> Update devstack.sh to use 2023.1 release

- ci/microshift.sh
The stale data can cause issues when starting microshift.
> Remove old microshift volume

- ci/radosgw.sh
The ci/radowsgw.sh script was attempting to run `apt-get install` without
first running `apt-get update`, which means that it can fail if the apt
cache is out-of-date [1].
This commit ensures that we call `apt-get update` to update the package
cache before attempting to install packages.
[1]: https://github.com/nerc-project/coldfront-plugin-cloud/actions/runs/4948674599/jobs/8850412133#step:5:24
> Add missing apt-get update to radosgw setup script

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
- src/coldfront_plugin_cloud/tests/base.py
- src/coldfront_plugin_cloud/tests/unit/test_calculate_quota_unit_hours.py
- src/coldfront_plugin_cloud/utils.py
- test-requirements.txt
This PR implements the management command `coldfront calculate_quota_unit_hours --start <start> --end <end>` that generates the  CSV invoice for the given period.
Some minor polish is still missing but it's operational.
> Implements the command to generate storage invoices

- src/coldfront_plugin_cloud/management/commands/list_cloud_allocations.py
This adds a new django admin management command: `list_cloud_allocations`. This prints a list of all cloud allocations (ie type openstack or openshift) and their attributes in either json (default) or csv format.
> add management command to list cloud allocations

- src/coldfront_plugin_cloud/openshift.py
This implicitly applies the following label to all projects which is required in order for them to show up as available projects/namespace in the RHODS/OpenDataHub dashboard:
```
opendatahub.io/dashboard: "true"
```
**NOTE**: Depends on https://github.com/CCI-MOC/openshift-acct-mgt/pull/98
> openshift: add rhods ns labels by default

- ci/radosgw.sh
This fixes an issue with the radosgw portion of the CI/CD pipeline due to an upstream issue/change with ceph-exporter related to the metrics setup on the cluster. This patch simply disables setting up the monitoring stack altogether given that the metrics setup is not used by this pipeline.
This patch also doubles the size of the OSDs given that the most recent version of ceph deployed by cephadm 17.2.6-0ubuntu0.22.04.1 requires more space. This was determined by the appearance of out-of-space errors
in OSD logs on an external test VM.
In addition to these changes, this patch also disables configuring firewalld given that it's not installed and not necessary for the CI/CD pipeline.
> fix recent radosgw CI/CD pipeline failures

- src/coldfront_plugin_cloud/openshift.py
This was causing the following error when creating new OpenShift projects:
```
coldfront_plugin_cloud.openshift.ApiException: 400: {"msg":"Unexpected
response from OpenShift API: Project in version \"v1\" cannot be
handled as a Project: json: cannot unmarshal bool into Go struct
field ObjectMeta.metadata.labels of type string"}
```
related: #115
> fix default RHODS label to use strings

- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/tasks.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
The default GPU quota multiplier should have been 0 given that we don't want a user to have access to a GPU until they explicitly request one via coldfront. Also updated the tests to include requesting an OpenShift GPU.
> fix default GPU quota and update tests

- .github/workflows/test-py39-functional-microshift.yaml
Addressing #124, the cause of the microshift test failures was because the action file used an outdated version of the account-management platform. At some point, a feature was added to this cloud-plugin to set quota limits on GPU resources. However, the Github Action file was not appropriately updated.
This is fixed by changing the version of account-management to the latest-in-time, commit 6fdbf84e12cf67fc0e288df72788fa77d976ff0e
Closes #124
> #124 Updated version of account-manager on github action file

- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/management/commands/list_cloud_allocations.py
- src/coldfront_plugin_cloud/management/commands/register_cloud_attributes.py
- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/tests/functional/openstack/test_allocation.py
- src/coldfront_plugin_cloud/tests/unit/test_attribute_migration.py
This patch explicitly defines all attribute configuration in the coldfront_plugin_cloud.attributes module. Previously, these settings were implied by conventions around the naming and organization of the attributes within the attributes module. This makes it easier to handle additional use cases as requirements change over time.
This patch also introduces two new dataclasses, `CloudResourceAttribute` and `CloudAllocationAttribute`, for storing both the attribute name and settings. The `RESOURCE_ATTRIBUTES`, `ALLOCATION_ATTRIBUTES`, and `ALLOCATION_QUOTA_ATTRIBUTES` lists are now lists of these dataclasses.
The second commit in this PR makes the institution-specific code attribute editable which was missed in #138
> explicitly define attribute configuration

- .github/workflows/test-py39-functional-microshift.yaml
- ci/microshift.sh
Addressing #91, the Github action file is changed to use the public image on ghcr. The unit tests should pass if the [related PR ](https://github.com/CCI-MOC/openshift-acct-mgt/pull/101)in `acct-manager` is accepted first.
> Action fix

- src/coldfront_plugin_cloud/openstack.py
- src/coldfront_plugin_cloud/tests/functional/openstack/test_allocation.py
Comparison with `if` returned the same for 0 values as for None.
Closes #141
> Fix quota for zero values

- src/coldfront_plugin_cloud/openshift.py
This adds the `modelmesh-enabled: true` label to all new projects by default. This is another rhods-specific label required in order to use a model mesh server within RHODS. Without it users run into errors similar to the following:
> pods "modelmesh-serving-saas-7994599679-" is forbidden: error looking up service account software-application-innovation-lab-sail-projects-fcd6dfa/modelmesh-serving-sa: serviceaccount "modelmesh-serving-sa" not found
> rhods: add modelmesh-server label

- requirements.txt
- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
Introduces the options
* `--upload-to-s3` which will upload the generated CSV from `coldfront calculate_storage_gb_hours`.
* `--s3-endpoint-url` and `--s3-bucket` to configure the destination S3 compatible store and bucket.
* `--invoice-month` which defaults to the month of the start date. This replaces the first column which was Interval.
Additionally
* Provides default for --start -> yesterday
* Provides default for --end -> today
Requires setting the environment variables
* S3_INVOICING_ACCESS_KEY_ID
* S3_INVOICING_SECRET_ACCESS_KEY
It will upload two copies of the invoice using the below format (one for archiving and timestamped and one as a working copy)
/Invoices/<INVOICE_MONTH>/Service Invoices/<SERVICE> <INVOICE_MONTH>.csv /Invoices/<INVOICE_MONTH>/Archive/<SERVICE> …
> Enable uploading generated invoice to S3

- ci/devstack-config-ip.sh
- ci/devstack-mapping.json
- ci/devstack-test-oidc.py
- ci/devstack.sh
- ci/run_functional_tests_openstack.sh
- src/coldfront_plugin_cloud/tests/functional/openstack/test_allocation.py
Closes #149 I edited the devstack functional test to use upstream Keystone's OIDC plugin. A few files from the [old plugin repo](https://github.com/knikolla/devstack-plugin-oidc) were copied and embedded in devstack.sh since I don't know a better place to put them. I am happy to relocate these files given advice.
it is important to note that sometimes the functional test for Openstack fails because one of the [plugin's setup script ](https://github.com/openstack/keystone/blob/4121cf6cb7c3d5e585df827d72e08296664f7326/devstack/tools/oidc/setup_keycloak_client.py#L29)would fail to access an endpoint in the Keycloak container. I am currently investigating the cause, or at least a solution to this failure.
> Migrating to using upstream keystone oidc plugin

- ci/devstack-mapping.json
- ci/devstack.sh
Due to inconsistent behavior when running the Openstack functional test in Github Actions, I have removed the OIDC plugin from the test.
> Improving test reliability by removing OIDC plugin from Openstack functional test

- setup.cfg
- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
- setup.cfg was missing the `boto3` library, therefore it wasn't installed in the `coldfront-nerc` container.
- String quotes were incorrect in one instance, causing the script to fail.
- Auto-complete suggested `add_option` confusing argparse for optparse. Fixed correct usage for argparse, changing the method from add_option to add_argument.
> Fix missing dependency, incorrect string quotes and argparse method

- src/coldfront_plugin_cloud/management/commands/migrate_fields_of_science.py
- src/coldfront_plugin_cloud/tests/base.py
- src/coldfront_plugin_cloud/tests/unit/test_migrate_field_of_science.py
I've moved the PR for field of science migration over here from [`coldfront-plugin-api`](https://github.com/nerc-project/coldfront-plugin-api/pull/38)
---
Closes https://github.com/nerc-project/coldfront-nerc/issues/92, I've added a Django management command to allow the migration of field of sciences.
The command requires that a tab-seperated mapping csv is provided, and can allow the migration to new, or already existing fields of sciences.
> Added management command to migrate field of sciences

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
This switches the PI field in invoices to use email instead.
Related to https://github.com/nerc-project/coldfront-plugin-api/issues/39
> Return PI email in storage invoices

- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/openstack.py
- src/coldfront_plugin_cloud/tests/functional/openstack/test_allocation.py
This set of patches makes the following changes:
- set swift/object/radosgw quota to 1 in the case that the quota defined in coldfront is <= 0
- catch and log exceptions when calling set_quota in `validate_allocations` command (openstack and openshift)
- handle zero value openshift quotas in `validate_allocations`
> openstack: require swift/object/radosgw quotas to be >= 0

- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
The quota value returned from swift's head_account function returns a string not an integer.
> validate: fix object store quota value comparison

- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/management/commands/register_cloud_attributes.py
Fix for #163
The following Allocation attributes are changed:
- OpenStack Volume Quota --> OpenStack Number of Volumes Quota
- OpenStack Compute RAM Quota --> OpenStack Compute RAM Quota (MiB)
- OpenStack Volume GB Quota --> OpenStack Volume Quota (GiB)
- ~~OpenStack Swift Quota in Gigabytes --> OpenStack Swift Quota (GiB)~~
- OpenShift Limit on RAM Quota (MB) --> OpenShift Limit on RAM Quota (MiB)
- OpenShift Limit on Ephemeral Storage Quota (GB) --> OpenShift Limit on Ephemeral Storage Quota (GiB)
- OpenShift Request on Storage Quota (GB) --> OpenShift Request on Storage Quota (GiB)
> renamed the attributes with GiB and MiB removing GB and MB

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
Closes #157, Cost will now be rounded to 2 decimal points
Rate will be rounded to 6 decimal points, since the Openshift Gb/hr rates at the time of this commit is $0.000009
> Added rounding to Cost and Rate for storage invoice

- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/management/commands/convert_swift_quota_to_gib.py
- src/coldfront_plugin_cloud/management/commands/register_cloud_attributes.py
- src/coldfront_plugin_cloud/openstack.py
Closes #162. A one-time command is added which will set the Swift quota of every allocation from GB to GiB. The Swift quota attribute name has been appropriately renamed
> Convert Swift quotas from GB to GiB

- .github/workflows/test-py39-functional-microshift.yaml
- setup.cfg
Closes #172 
`simplejson` was not part of the requirements when it should've been. Probably one of our dependencies dropped it, leading to it not being installed through them.
Microshift was being stuck in waiting. I couldn't reproduce the same issue on a 22.04 machine, so I just updated the Ubuntu of the action to 22.04.
> Fix broken CI

- src/coldfront_plugin_cloud/tests/unit/test_calculate_quota_unit_hours.py
- src/coldfront_plugin_cloud/utils.py
Closes #170. I have introduced 3 test cases for storage billing with change requests (CR), 2 of which are intended to fail. The 3 test cases are:
1. Testing when there is a CR to decrease the quota
2. A CR to increase the quota
3. Multiple CRs to decrease the quota
The test cases involving decreasing the quota should fail, and demonstrates the bug that I will explain below.
From what I read in the billing code, our intention with CRs is that when an allocation's storage quota decreases, this decreased value becomes effective (for billing purposes) when the CR for it is created, not when the CR is approved (or the time at which the quota actually decreased). Due to this [statement](https://github.com/nerc-project/coldfront-plugin-cloud/blob/f7a4dc2f2d212f720fd201bab87971e6c508703d/src/coldf …
> Fixed billing with decreasing allocation change requests

- requirements.txt
- setup.cfg
- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
Closes #167 , I have modified `calculate_storage_gb_hours` to use the storage rates stored in the `nerc-rates` repo.
> Implemented 'nerc-rates' for storage invoicing

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
- src/coldfront_plugin_cloud/tests/unit/test_calculate_quota_unit_hours.py
- src/coldfront_plugin_cloud/utils.py
Closes #166. Added an optional CLI argument which allows passing in a txt file containing excluded time intervals. Each line in the txt file should contain a date range that we want to exclude from billing, formatted as
"%Y-%m-%d,%Y-%m-%d". An example line could be "2023-02-01,2023-02-03".
The time period excluded from billing starts from the first second of the start date, and ends on the last second of the end date. This means it is possible for the excluded date range to start and end on the same day.
Also fixed a minor typo.
> Support excluding time intervals during storage invoicing and fixed typo

- .github/workflows/test-py39-unit.yaml
The unit test workflow was reporting "Running functional tests" in the
log, which was confusing.
> Fix step name in unit test workflow

- .github/dependabot.yaml
Ensure that we are using recent action versions in our
github workflows.
> Have dependabot manage gitub action versions

- requirements.txt
- setup.cfg
- src/coldfront_plugin_cloud/tests/base.py
- src/coldfront_plugin_cloud/tests/unit/test_attribute_migration.py
Always call `initial_setup` with `-f` option to avoid the "Do you want to
proceed?" interactive prompt.
> Avoid interactive prompts during unit tests

- ci/devstack.sh
- ci/microshift.sh
- ci/run_functional_tests_openshift.sh
- ci/run_functional_tests_openstack.sh
- ci/run_unit_tests.sh
- ci/setup-oc-client.sh
- ci/setup-ubuntu.sh
- ci/setup.sh
Executable shell scripts should always start with a shebang line
(#!/path/to/shell) specifying which interpreter to use for the script. This
ensures, for example, that in Debian/Ubuntu environments, scripts that
expect Bash semantics are actually using Bash rather than `/bin/sh`.
Scripts that are missing a shebang line will also fail to execute when
executed directly (rather than via a shell):
>>> import os
>>> os.execve('./test.sh', ['test.sh'], {})
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
OSError: [Errno 8] Exec format error: './test.sh'
> Add missing shebang (#!) lines

- README.md
- ci/run_functional_tests_openstack.sh
- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/esi.py
- src/coldfront_plugin_cloud/management/commands/add_openstack_resource.py
- src/coldfront_plugin_cloud/management/commands/register_cloud_attributes.py
- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/openstack.py
- src/coldfront_plugin_cloud/tasks.py
- src/coldfront_plugin_cloud/tests/base.py
- src/coldfront_plugin_cloud/tests/functional/esi/test_allocations.py
- src/coldfront_plugin_cloud/tests/functional/openstack/test_allocation.py
- src/coldfront_plugin_cloud/tests/unit/test_attribute_migration.py
Closes #135 To integrate ESI and make use of the existing code, I have made a few small restructuring choices. There’s too many to list, so I will be ready for everyone’s questions on my code changes. 
The ESI allocator object, implemented in `esi.py`, subclasses from the Openstack allocator, with a few functions overridden. The ESI allocator only makes quotas for floating IPs and networks. The appropriate Allocation Attributes have been added to `attributes.py`
The functional test for the ESI integration uses the same Openstack cluster put up by `test-py38-functional-devstack.yaml`. `ci/run_functional_tests_openstack.sh` has been edited to also create an ESI coldfront resource and to run the ESI functional tests.
> Integrate ESI into Coldfront

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
- src/coldfront_plugin_cloud/tests/unit/test_calculate_quota_unit_hours.py
- src/coldfront_plugin_cloud/utils.py
This PR has three commits with overall the following changes
- Changes the command line parameter `--exclude-date-ranges` to `--exclude-time-ranges` and its parsing method to ISO.
- Makes `--openshift-gb-rate` and `--openstack-gb-rate` parameters optional. This was required in this PR to allow adding a complete CLI call as part of the unit tests.
- Adds CLI calls in the unit tests for `calculate_storage_gb_hours` with and without the excluded time intervals. There was no tests exercising the above and therefore broken code had slipped in before. This also exposes an issue with the first commit were the time range wasn't properly being parsed.
- Only import `nerc-rates` when storage rate parameters aren't provided through the CLI. `nerc-rates` doesn't seem to work in Python 3.9 which is …
>  Support hours when providing outage intervals in billing

- ci/run_functional_tests_openshift.sh
- requirements.txt
- setup.cfg
- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/tests/unit/openshift/test_user.py
Closes #175. As the first step towards merging the account manager into our coldfront cloud plugin, the `get_federated_user` function in the Openshift allocator will now (through several functions) directly call the Openshift API. Much of the functions added are copied from the `moc_openshift` module in the account manager.
Aside from copying some functions,
implementation of this feature also involved:
- A new resource attribute `Identity Name` for the Openshift idp
- A new unit test for the `get_federated_user` function
- Changes to the CI file to enable these new unit tests
> Allow direct communication to Openshift API through `get_federated_user`

- ci/run_functional_tests_openshift.sh
- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/management/commands/add_openshift_resource.py
- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/tests/base.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
- src/coldfront_plugin_cloud/tests/unit/openshift/test_quota.py
- src/coldfront_plugin_cloud/tests/unit/openshift/test_user.py
Closes #187, this PR consists of two commits. The first one fixes an integration bug and will now require Openshift resources to specify two URLs, one to the account manager, and one to the Openshift API. The second implements the integration to the Openshift API. 
More details in the commit messages.
> Allow direct communication to Openshift Quota API

- .github/workflows/test-functional-microshift.yaml
- ci/run_functional_tests_openshift.sh
- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/management/commands/add_openshift_resource.py
- src/coldfront_plugin_cloud/management/commands/register_cloud_attributes.py
- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/openshift_vm.py
- src/coldfront_plugin_cloud/tasks.py
- src/coldfront_plugin_cloud/tests/base.py
- src/coldfront_plugin_cloud/tests/functional/openshift_vm/test_allocation.py
Closes nerc-project/operations#820. This PR consists of 2 commits. The first one updates the account manager pin, and the second contains the implementation for the new resource class. More details in the commit message.
> Implemented a new resource class for Openshift virtualization

- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/tasks.py
As a small improvement, this will make `tasks.UNIT_QUOTA_MULTIPLIERS` the source of truth for what quota attributes any given allocation should have, making the code a bit easier to manage. This will also somewhat simplify the coding required to add the Openshift Virtualization resource type.
> Refactored `validate_allocation` to use `tasks.UNIT_QUOTA_MULTIPLIERS` when determining what attributes an allocation should have

- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
Closes #196. Built on top #205. This PR consists on the last commit. More info in the commit message.
> Allow adding `nerc.mghpcc.org/allow-unencrypted-routes: 'true'` label to all pre-existing and future Openshift projects

- requirements.txt
- setup.cfg
- test-requirements.txt
Due to ColdFront upstream hard pinning python-memcached, and the OpenStack libraries installing their own version that was a different version, we used to pin memcached to avoid the incompatibility.
We'll now depend on the version that ColdFront pulls in through its own requirements.
> Remove memcached pin

- .github/workflows/test-functional-microshift.yaml
- .github/workflows/test-functional-microstack.yaml
- .github/workflows/test-unit.yaml
- setup.cfg
Closes https://github.com/nerc-project/coldfront-plugin-cloud/issues/217. Removed because of successful tool migration to python 3.12.
> Remove python 3.9 checks from CI tests 

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
- Add "Cluster Name" in invoice header
- Write Resource Name instead of Resource Type Name
Related #221
> Fix Cluster Name in invoice

- src/coldfront_plugin_cloud/management/commands/add_openshift_resource.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
- src/coldfront_plugin_cloud/tests/unit/openshift/test_rbac.py
- src/coldfront_plugin_cloud/tests/unit/openshift/test_user.py
Closes #186. Dependant on #224, this PR consists of the last commit. After this, #205, #219, and #224 merges, we can remove the dependancy on `openshift-acct-mgt`.
> Allow direct communication to Openshift RBAC API

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
While testing `calculate_storage_gb_hours`, I realized that the default start and end arguments were not timezone aware, but the django timestamps for event times are. I've added timezone awareness to default start and end date arguments. 
Also fixed `s3-bucket-name` cli argument name.
This is blocking https://github.com/nerc-project/coldfront-nerc/pull/135
> Fix `calculate_storage_gb_hours`

- README.md
- ci/run_functional_tests_openshift.sh
- src/coldfront_plugin_cloud/management/commands/add_openshift_resource.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/tests/base.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
- src/coldfront_plugin_cloud/tests/functional/openshift_vm/test_allocation.py
- src/coldfront_plugin_cloud/tests/unit/test_calculate_quota_unit_hours.py
Some clean-up. Now that the account manager is no longer used. Do we plan on nuking that repo anytime soon?
> Removed references to openshift-acct-mgt

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
Closes https://github.com/issues/assigned?issue=CCI-MOC%7Cnerc-rates%7C45. Migrate of our codebases to use the more specific NESE Storage GB Rate rate when referring to storage
> Migrate to use NESE Storage GB Rate

- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/tests/base.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
> Allow validation of allocations with status `Active (Needs Renewal)`
