nerc-project/coldfront-plugin-cloud

- src/coldfront_plugin_openstack/management/commands/add_openstack_resource.py
> replace dashes with underscores in option key names

- .github/workflows/test-py39-functional.yaml
- setup.cfg
- test-requirements.txt
- adds test-specific requirements.txt file and updates github action to use it
- simplify coldfront dependency to just `coldfront >= 1.0.4` to hopefully alleviate some dep issues
> test against specific coldfront commit

- src/coldfront_plugin_openstack/tests/functional/test_allocation.py
- Fixed incorrect user being checked on add_user.
- Added coverage for removing users.
- Added coverage for adding existing users.
> Improve CI coverage for users

- src/coldfront_plugin_openstack/management/commands/add_openstack_resource.py
> Fix typo in add_openstack_resource management command

- src/coldfront_plugin_openstack/signals.py
- src/coldfront_plugin_openstack/tasks.py
> Wait for project creation when adding user to project

- src/coldfront_plugin_openstack/base.py
- src/coldfront_plugin_openstack/openstack.py
- src/coldfront_plugin_openstack/tasks.py
- src/coldfront_plugin_openstack/tests/functional/test_allocation.py
Review commit by commit, rather than all at once.
> Refactor to prepare for openshift support

- src/coldfront_plugin_openstack/attributes.py
For consistency with the other attributes
> prefix gpu attr name with OpenStack

- src/coldfront_plugin_openstack/management/commands/count_gpu_usage.py
Implements the command `count_gpu_usage --flavor <flavor_name>` which
counts the number of GPU instances and compares it with the allowance.
Closes #51
> Count GPU usage

- src/coldfront_plugin_openstack/management/commands/validate_allocations.py
> Fix validate_allocations failing on not existing project id

- src/coldfront_plugin_cloud/base.py
- src/coldfront_plugin_cloud/openstack.py
- src/coldfront_plugin_cloud/tasks.py
> Allow Resource Allocators to define a project name character limit

- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
The attribute will be set based on the current quota value.
Closes #41
> Populate missing attributes on resource allocations

- src/coldfront_plugin_cloud/openstack.py
Turns out, replacing the url attribute is not the same as passing preauthurl. Removed the swiftclient_change_project function in favor of simply constructing the initial swift client with the proper preauthurl kwarg if a project_id is specified.
> fix preauth url config in swift client

- .github/workflows/test-py38-functional-devstack.yaml
- .github/workflows/test-py39-functional-microshift.yaml
- README.md
- ci/microshift.sh
This PR adds documentation for OpenShift and fixes the broken CI.
Closes #79
> Update docs for OpenShift and fix CI

- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
this does the thing, but could look nicer and maybe use some refactoring. Looking for feedback.
> Extend validation command to validate openshift quotas

- src/coldfront_plugin_cloud/openstack.py
We still haven't fully ironed out the implementation of quotas for RGW based object storage. But in that scenario, applying quotas fails and the executions stops and fails to apply volume quotas.
We want to warn that something is wrong, but not outright fail, so that execution can continue and volume quotas apply.
> Warn but don't fail on swift quotas

- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/management/commands/register_cloud_attributes.py
> Add missing unit (MB) for OpenShift RAM Quota

- .github/workflows/test-py39-functional-microshift.yaml
- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/openstack.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
- src/coldfront_plugin_cloud/tests/functional/openstack/test_allocation.py
Closes https://github.com/nerc-project/coldfront-plugin-cloud/issues/81 and https://github.com/nerc-project/coldfront-plugin-cloud/issues/90
> Sync users with `validate_allocations` command

- ci/run_functional_tests_openshift.sh
- ci/run_functional_tests_openstack.sh
- ci/run_unit_tests.sh
- test-requirements.txt
> Add code coverage reports to unit and functional tests

- src/coldfront_plugin_cloud/attributes.py
- src/coldfront_plugin_cloud/management/commands/validate_allocations.py
- src/coldfront_plugin_cloud/tasks.py
> add institution-specific code attribute to cloud allocations

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
The variable attributes was shadowing the module attributes.
> Fix issue from variable shadowing

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
Adds institution specific code to generated invoice.
> Add institution specific code to invoice

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
> Fix incorrect code block split into 2 lines

- src/coldfront_plugin_cloud/management/commands/add_openshift_resource.py
- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/tests/unit/openshift/test_quota.py
closes https://github.com/nerc-project/coldfront-plugin-cloud/issues/213. Made minor clerical adjustments. Add reason_not_found helper.
> Resolve nits regarding direct communications to Openshift API

- src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
Closes #221. I just need confirmation on the resource names used in production Coldfront
> Added `Cluster Name` column to storage invoice

- src/coldfront_plugin_cloud/openshift.py
- src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py
- src/coldfront_plugin_cloud/tests/unit/openshift/base.py
- src/coldfront_plugin_cloud/tests/unit/openshift/test_project.py
- src/coldfront_plugin_cloud/tests/unit/openshift/test_quota.py
- src/coldfront_plugin_cloud/tests/unit/openshift/test_user.py
Closes #185. More info in the commit message.
> Allow direct communication to Openshift Projects API
